{
  "blobs" : {
    "_iot_endpoint_config" : {
      "phase" : "final",
      "status" : {
        "message" : "While resetting connection",
        "detail" : "java.lang.RuntimeException: While resetting connection\n\tat daq.pubber.Pubber.resetConnection(Pubber.java:1164)\n\tat daq.pubber.Pubber.maybeRedirectEndpoint(Pubber.java:1120)\n\tat daq.pubber.Pubber.deferredConfigActions(Pubber.java:695)\n\tat daq.pubber.Pubber.periodicUpdate(Pubber.java:629)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:833)\nCaused by: java.lang.RuntimeException: While attempting to start connection\n\tat daq.pubber.Pubber.startConnection(Pubber.java:803)\n\tat daq.pubber.Pubber.resetConnection(Pubber.java:1161)\n\t... 9 more\nCaused by: java.lang.RuntimeException: Failed connection attempt after retries\n\tat daq.pubber.Pubber.startConnection(Pubber.java:800)\n\t... 10 more\n",
        "category" : "blobset.blob.apply",
        "level" : 500
      },
      "generation" : "2023-07-28T20:21:12Z"
    }
  },
  "timestamp" : "2023-07-28T20:22:28Z",
  "version" : "1.4.1"
}