{
  "blobs" : {
    "_iot_endpoint_config" : {
      "phase" : "final",
      "status" : {
        "message" : "While resetting connection",
        "detail" : "java.lang.RuntimeException: While resetting connection\n\tat daq.pubber.Pubber.resetConnection(Pubber.java:550)\n\tat daq.pubber.PubberUdmiPublisher.maybeRedirectEndpoint(PubberUdmiPublisher.java:667)\n\tat daq.pubber.PubberUdmiPublisher.deferredConfigActions(PubberUdmiPublisher.java:500)\n\tat daq.pubber.Pubber.periodicUpdate(Pubber.java:402)\n\tat java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)\n\tat java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: java.lang.RuntimeException: While attempting to start connection\n\tat daq.pubber.Pubber.startConnection(Pubber.java:424)\n\tat daq.pubber.Pubber.resetConnection(Pubber.java:548)\n\t... 9 more\nCaused by: java.lang.RuntimeException: Failed connection attempt after retries\n\tat daq.pubber.Pubber.startConnection(Pubber.java:422)\n\t... 10 more\n",
        "category" : "blobset.blob.apply",
        "timestamp" : "2024-11-06T17:33:02Z",
        "level" : 500
      },
      "generation" : "2024-11-06T17:31:57Z"
    }
  },
  "timestamp" : "2024-11-06T17:33:07Z",
  "version" : "1.5.2"
}